### ISSUE TITLE
實作學生驗證功能前端頁面

### ISSUE THREAD

**Issue by hashman** [s9801077/Equipment-management-system#13]
目前前端頁面大致上已經刻好了，可以直接到 kktix 上面下載去年的學生訂單來進行使用測試，前端需要幾點幫忙

# 需求

1. 點選「 Upload 」按鈕透過 `api/student/upload` 進行載入動作，載入前端
2. 點選驗證通過會呼叫 post `api/student`傳入 row 的資料進行儲存 or 更新
3. 購票日期、姓名、 Email 、學校名稱、備註欄位皆可以進行更新
4. 增加刪除按鈕將這個存在的 record 移除資料庫
> 這個可以晚一點，我目前只有開出刪除的 api 還沒有將資料上傳的時候與資料庫進行比對
5. 圖片支援可以滑過放大 or 點選另開新頁
6. PDF 看看有沒有 library 可以支援直接 Preview 如果沒有就一樣另開新頁就好

# 資料庫欄位說明

* id int auto_increment
* verify_year smallint 驗證年， like 2017, 2018 等
* verify_user_id int 驗證使用者，對應到 users table 的 id
* order_id int kktix 提供的訂單編號
* register_no int kktix 提供的報名序號
* purchase_date varchar 購票日期
* name varchar 姓名
* email varchar
* school_name text 學校名稱
* file_link text kktix 提供的檔案網址
* comment text 審核者備註

**Comment by s9801077** [comment]
Resolve #15

**Comment by s9801077** [comment]
resolve #15

**Comment by s9801077** [comment]
resolved
